default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DB_HOST") %>
  port: <%= ENV.fetch("DB_PORT") %>
  url: <%= ENV.fetch("DATABASE_URL") %>

development:
  <<: *default
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "123456") %>
  database: <%= ENV.fetch("DB_NAME_DEVELOPMENT", "app_development") %>

test:
  <<: *default
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "123456") %>
  database: <%= ENV.fetch("DB_NAME_TEST", "app_test") %>

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_PROD_URL") %>
  database: <%= ENV.fetch("DB_NAME_PRODUCTION") %>
  username: <%= ENV.fetch("DB_USERNAME_PRODUCTION") %>
  password: <%= ENV.fetch("MAINOBLOG_DATABASE_PASSWORD") %>
