default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV.fetch("DB_USERNAME", postgres) %>
  password: <%= ENV.fetch("DB_PASSWORD", 123456) %>
  host: <%= ENV.fetch("DB_HOST") %>
  port: <%= ENV.fetch("DB_PORT") %>
  # url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_DEVELOPMENT", "app_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST", "app_test") %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: <%= ENV.fetch("DB_NAME_PRODUCTION") %>
  username: <%= ENV.fetch("DB_USERNAME_PRODUCTION") %>
  password: <%= ENV["MAINOBLOG_DATABASE_PASSWORD"] %>
