name: Ruby on Rails CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: mainoblog_test
        ports:
          - 5432:5432
    env:
      RAILS_ENV: test
      PGHOST: 127.0.0.1
      PGUSER: postgres
      PGPASSWORD: 123456
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME_DEVELOPMENT: ${{ secrets.DB_NAME_DEVELOPMENT }}
      DB_NAME_TEST: ${{ secrets.DB_NAME_TEST }}
      DB_NAME_PRODUCTION: ${{ secrets.DB_NAME_PRODUCTION }}
      DB_USERNAME_PRODUCTION: ${{ secrets.DB_USERNAME_PRODUCTION }}
      MAINOBLOG_DATABASE_PASSWORD: ${{ secrets.MAINOBLOG_DATABASE_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Prepare database
        run: bin/rails db:setup

      - name: Run tests
        run: bundle exec rspec

      - name: Lint Ruby files
        run: bundle exec rubocop
